[custom]
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/fbinba3955/KianaJson/master/rule/self_direct.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/BanAD.list
ruleset=🔰 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🔰 节点选择,https://raw.githubusercontent.com/fbinba3955/KianaJson/master/rule/self_proxy.list
ruleset=🔰 节点选择,https://raw.githubusercontent.com/fbinba3955/KianaJson/master/rule/self_emby.list
ruleset=🔰 节点选择,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Binance/Binance.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=📹 油管视频,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTubeMusic.list
ruleset=🌏 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Copilot/Copilot.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Claude/Claude.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OpenAI/OpenAI.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Gemini/Gemini.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/fbinba3955/KianaJson/refs/heads/master/rule/self_ai.list
ruleset=🔰 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
custom_proxy_group=🔰 节点选择`select`[]🌀 自动选择`[]❤️‍🔥 JMS`[]🪅 独角兽`[]DIRECT`.*
custom_proxy_group=🌀 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=📲 电报消息`select`[]❤️‍🔥 JMS`[]🔰 节点选择`[]🌀 自动选择`[]🪅 独角兽`.*
custom_proxy_group=📹 油管视频`select`[]🔰 节点选择`[]🌀 自动选择`[]❤️‍🔥 JMS`[]🪅 独角兽`.*
custom_proxy_group=🌍 国外媒体`select`[]🔰 节点选择`[]🌀 自动选择`[]❤️‍🔥 JMS`[]DIRECT`.*
custom_proxy_group=🌏 国内媒体`select`[]DIRECT`[]🔰 节点选择`.
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🔰 节点选择`[]🌀 自动选择`.*
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🔰 节点选择`[]🌀 自动选择`[]❤️‍🔥 JMS`[]🪅 独角兽`.*
custom_proxy_group=❤️‍🔥 JMS`url-test`(c10s4)`(c10s3)`(c10s2)`(c10s1)`(c10s5)`http://www.gstatic.com/generate_204`180,,50
custom_proxy_group=🪅 独角兽`url-test`((?=.*ˣ¹)(?=.*(?:香港|日本|台湾|新加坡|HK|SG|JP|TW)))`http://www.gstatic.com/generate_204`180,,50

#include_remarks=(日|JP|c10s4|美|US|港|HK|新加坡|SG|狮|土|TR|英|UK|GB|c10s1|c10s2|c10s3|台|TW|c10s5|马来西亚|菲)
exclude_remarks=(临时|c10s801|官网|过期)
